#!/bin/bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r "$HOME/.dotfilesrc" ] && source "$HOME/.dotfilesrc";


load_dotfiles() {
    # load up any component-based bash config files
    # thanks to Sorpigal & SO for this
    # http://stackoverflow.com/a/7039579/901717
    config_files=()
    while IFS= read -d $'\0' -r file ; do
        if [[ -r "$file" ]]; then
            config_files=("${config_files[@]}" "$file")
        fi
    done < <(find "$HOME/.dotfiles" -d 2 -iname "*.bash" -print0)

    # source per-componenet path updates first
    for file in "${config_files[@]}"
    do
        if [[ "${file##*/}" =~ "path.bash" && -r "${file}" ]]; then
            source "${file}"
        fi
    done

    # if these files are readable, source them
    declare -a files=(
        $HOME/.dotfiles/shell/bash_options # Options
        $HOME/.dotfiles/shell/bash_exports # Exports
        $HOME/.dotfiles/shell/bash_aliases # Aliases
        $HOME/.dotfiles/*/functions/* # Functions
        $HOME/.dotfiles/shell/bash_prompt # Custom bash prompt
        $HOME/.dotfiles/shell/bash_paths # Path modifications
        $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
        $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    )
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done

    # source any other per-comonenet bash config next, except path & completions
    for file in "${config_files[@]}"
    do
        if [[ ! "${file##*/}" =~ "path.bash" && ! "${file##*/}" =~ "completion.bash" && -r "$file" ]]; then
            source "${file}"
        fi
    done

    # load completions last
    for file in "${config_files[@]}"
    do
        if [[ "${file##*/}" =~ "completion.bash" && -r "$file" ]]; then
            source "${file}"
        fi
    done
}

load_dotfiles
unset load_dotfiles
