#!/bin/bash

# Call pew's "workon" if .venv exists.
# adapted from--
# https://gist.github.com/clneagu/7990272
# which is modified from--
# http://justinlilly.com/python/virtualenv_wrapper_helper.html
# which is linked from--
# http://virtualenvwrapper.readthedocs.org/en/latest/tips.html#automatically-run-workon-when-entering-a-directory
check_virtualenv() {
    if [[ -e .venv ]]; then
        env=`cat .venv`
        if [[ "$env" != "${VIRTUAL_ENV##*/}" &&  $(pew ls | tr ' ' '\n' | grep -e "^${env}$") ]]; then
            pew workon $env
        fi
    fi
}
