#!/bin/bash

run_list() {

    printf "\nHere is a list of items that will be installed:\n"

    e_header "Homebrew Tools:"
    while read p; do
        printf "\t$p\n"
    done < ${DOTFILES_DIRECTORY}/brew/requirements.txt

    e_header "Homebrew Cask Apps:"
    while read p; do
        printf "\t$p\n"
    done < ${DOTFILES_DIRECTORY}/cask/requirements.txt

    e_header "Node.js Packages (global install):"
    while read p; do
        printf "\t$p\n"
    done < ${DOTFILES_DIRECTORY}/node/requirements.txt

    e_header "Python Packages:"
    while read p; do
        printf "\t$p\n"
    done < ${DOTFILES_DIRECTORY}/python/requirements.txt

}
