#!/bin/bash

run_list() {

cat <<EOT

Additional software to install

Browsers:
    Firefox
    Google Chrome
    Opera

Development:
    Filezilla
    iTerm 2
    ImageAlpha
    ImageOptim
    VirtualBox
    XAMPP
    Sublime Text
    Sequel Pro

Other:
    Alfred
    Divvy
    Dropbox
    Droplr
    Flux
    KeePassX
    LimeChat
    Network Connect
    Skype
    uTorrent
    VLC
EOT

}
