#!/bin/bash

# this assumes you're using apache & php-version
# $1 version string passed to php-version
switch_php() {
    if [[ $(type "php-version" 2> /dev/null) ]]; then
        php-version "$1"
        if [[ $? -eq 0 ]]; then
            local full_version=$(php --version | head -1 | awk '{print $2}')
            local major_version=$(echo ${full_version%.*} | sed -e 's,\.,,g')
            local php_module="$(brew --prefix)/Cellar/php${major_version}/${full_version}/libexec/apache2/libphp5.so"
            sed -Ee "s,^#?(LoadModule php5_module).*,\1 ${php_module}," /etc/apache2/httpd.conf > "$HOME/httpd.conf.bkp"
            sudo mv "$HOME/httpd.conf.bkp" /etc/apache2/httpd.conf
            sudo apachectl restart
        fi
    else
        echo "Error: requires php-version to be installed."
        echo "Head to https://github.com/wilmoore/php-version for details."
    fi
}
